CREATE TABLE T_YQJK_PARAM (
  ID VARCHAR2(32) PRIMARY KEY,
  TOKEN_URL VARCHAR2(200) NULL ,
  TOKEN_CONTENT_TYPE VARCHAR2(32) NULL ,
  CLIENT_ID VARCHAR2(32) NULL ,
  CLIENT_SECRET VARCHAR2(32) NULL ,
  GRANT_TYPE VARCHAR2(32) NULL ,
  API_URL VARCHAR2(200) NULL ,
  API_CONTENT_TYPE VARCHAR2(32) NULL ,
  PROCESS_NUM VARCHAR2(32) NULL ,
  STEP_NUM VARCHAR2(32) NULL ,
  RECEIVE_APP_ID VARCHAR2(32) NULL ,
  INVOKING_APP_ID VARCHAR2(32) NULL ,
  TYPE VARCHAR2(32) NULL
);
COMMENT ON TABLE T_YQJK_PARAM IS '应用检测信息表';
COMMENT ON COLUMN T_YQJK_PARAM.ID IS 'ID';
COMMENT ON COLUMN T_YQJK_PARAM.TOKEN_URL IS 'token的Url';
COMMENT ON COLUMN T_YQJK_PARAM.TOKEN_CONTENT_TYPE IS 'token标识请求类型';
COMMENT ON COLUMN T_YQJK_PARAM.CLIENT_ID IS '应用的Api Key';
COMMENT ON COLUMN T_YQJK_PARAM.CLIENT_SECRET IS '应用的Secret Key';
COMMENT ON COLUMN T_YQJK_PARAM.GRANT_TYPE IS '获取token的模式 默认implicit';
COMMENT ON COLUMN T_YQJK_PARAM.API_URL IS 'API网关的Url';
COMMENT ON COLUMN T_YQJK_PARAM.API_CONTENT_TYPE IS 'API网关标识请求类型';
COMMENT ON COLUMN T_YQJK_PARAM.PROCESS_NUM IS '方案编号 随机值，用于标识当前请求，建议以当前时间戳来作为内容';
COMMENT ON COLUMN T_YQJK_PARAM.STEP_NUM IS '步骤编号';
COMMENT ON COLUMN T_YQJK_PARAM.RECEIVE_APP_ID IS '接收方应用ApiKey';
COMMENT ON COLUMN T_YQJK_PARAM.INVOKING_APP_ID IS '发起方应用ApiKey';
COMMENT ON COLUMN T_YQJK_PARAM.TYPE IS '0：为可能密切接触者数据查询服务接口；1：为确诊和疑似病例数据查询服务接口';

INSERT INTO T_YQJK_PARAM (ID, TOKEN_URL, TOKEN_CONTENT_TYPE, CLIENT_ID, CLIENT_SECRET, GRANT_TYPE, API_URL, API_CONTENT_TYPE, PROCESS_NUM, STEP_NUM, RECEIVE_APP_ID, INVOKING_APP_ID, TYPE)
VALUES ('2', 'HTTP://11.33.1.46:9881/GATEWAY-SERVER/LDXTOAUTH/TOKEN', 'APPLICATION/JSON', '0556EFB2E7F5A', '0556EF6F24952', 'IMPLICIT', 'HTTP://11.33.1.46:9881/GATEWAY-SERVER/LD/INVOK', 'APPLICATION/JSON', NULL, 'BZ010000200217142944990391', 'D3817C5688202', '0556EFB2E7F5A', '0');
INSERT INTO T_YQJK_PARAM (ID, TOKEN_URL, TOKEN_CONTENT_TYPE, CLIENT_ID, CLIENT_SECRET, GRANT_TYPE, API_URL, API_CONTENT_TYPE, PROCESS_NUM, STEP_NUM, RECEIVE_APP_ID, INVOKING_APP_ID, TYPE)
VALUES ('1', 'HTTP://11.33.1.46:9881/GATEWAY-SERVER/LDXTOAUTH/TOKEN', 'APPLICATION/JSON', '0556EFB2E7F5A', '0556EF6F24952', 'IMPLICIT', 'HTTP://11.33.1.46:9881/GATEWAY-SERVER/LD/INVOK', 'APPLICATION/JSON', NULL, 'BZ010000200217151347059206', 'D3817C5688202', '0556EFB2E7F5A', '1');


CREATE TABLE T_YQJK_AUDIT_LOG(
  ID VARCHAR2(32) PRIMARY KEY,
  QQR_ID VARCHAR2(32) NOT NULL,
  QQR_DWDM VARCHAR2(15) NOT NULL,
  QQR_DWMC VARCHAR2(200) NOT NULL,
  QQR_XM VARCHAR2(50) NOT NULL,
  QQR_SFZHM VARCHAR2(18) NOT NULL,
  CXSY VARCHAR2(50),
  BXCR_XM VARCHAR2(50) NOT NULL,
  BCXR_SFZHM VARCHAR2(18) NOT NULL,
  INTERFACE_TYPE VARCHAR2(1) NOT NULL,
  RMI_STATUS VARCHAR2(1) NOT NULL,
  RMI_RETURN VARCHAR2(2000) NOT NULL,
  OPERATE_TIME VARCHAR2(14)
);

COMMENT ON TABLE T_YQJK_AUDIT_LOG IS '疫情监控审计日志表';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.ID IS '唯一标识符';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.QQR_ID  IS '发起请求的用户的ID';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.QQR_DWDM  IS '发起请求的用户的单位代码';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.QQR_DWMC  IS '发起请求的用户的单位名称';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.QQR_XM  IS '发起请求的用户的姓名';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.QQR_SFZHM  IS '发起请求的用户的身份证号码';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.CXSY  IS'前台页面传递过的条件:查询事由';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.BXCR_XM  IS '前台页面传递过的条件:被查询人姓名';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.BCXR_SFZHM  IS '前台页面传递过的条件:被查询身份证号码';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.INTERFACE_TYPE  IS '被调用的接口类型:0-可能密切接触者查询服务,1-确诊和疑似病例查询服务';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.RMI_STATUS  IS '远程调用状态:1-暂无匹配记录,2-调用结果比中,3-远程调用异常';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.RMI_RETURN  IS '远程调用状态返回的JSON格式的请求结果';
COMMENT ON COLUMN T_YQJK_AUDIT_LOG.OPERATE_TIME   IS '操作时间';
